name: Build and Publish package
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean compile assembly:single --file pom.xml -P prod
      - run: mkdir staging && cp target/*.jar staging
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: srserver-pkg
          path: staging
      - name: Make Release
        uses: softprops/action-gh-release@v1
        with:
          files: staging/*.jar
